apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/00-prereqs/
  - ../../../components/03-gpu-operators/
  - ../../../components/04-gpu-dashboard/
  - ../../../components/07-authorino-operator/
  - ../../../components/08-serverless-operator/
  - ../../../components/09-servicemesh-operator/